<?php
    $this->headLink()->appendStylesheet('/css/fam-icons.css');
?>
<div class="container">
    <h2>Accueil</h2>

    
            <a href="admin/category"><i class="fam-cog"></i> Catégories</a>
   
      
            Gestion des catégories
       
  
    <hr />
 
            <a href="#"><i class="fam-page"></i> Evènements</a>
     
   
            Gestion des Evènements

   
    <hr />

            <a href="#"><i class="fam-user"></i> Utilisateurs</a>
    
            Gestion des utilisateurs
</div>
